### PR TITLE
Feature/srm hardware map refactor

### LINKED ISSUE #96: Hardware map mismatch to real hardware
Need to fix mismatch:
* PCB to hardware setup in .ico file in the project
* hardware setup to hardware map class

### PR DESCRIPTION
**Pull request by Vavat**
Fixes #96.
Remap MCU pins to correspond to changes to the PCB design.
* Reduce number of control channels to 8.
* Remove I2C.
* Add new sensor for thermal evaporator.
* Add mains power control channels.
* Add SPI PMOD expansion.

### CODE REVIEW

**Review by Niuslar — CHANGES_REQUESTED** [review]
The ADC1 configuration needs to have Continuous Conversion Mode  Enabled 
image

**Comment by Vavat** [comment]
> The ADC1 configuration needs to have Continuous Conversion Mode Enabled image

Fixed.

**Review by Niuslar — CHANGES_REQUESTED** [review]
Sorry, testing the channels I realised that in the CAdcData header, ADC_CHANNELS needs to be changed to 13 because this defines the size of the DMA buffer. Maybe we could open a ticket to see if we can update this number automatically. 
image

**Comment by Vavat** [comment]
> Sorry, testing the channels I realised that in the CAdcData header, ADC_CHANNELS needs to be changed to 13 because this defines the size of the DMA buffer. Maybe we could open a ticket to see if we can update this number automatically. image

Fixed.

**Review by Niuslar — APPROVED** [review]

**Pull request merged**
